Added first implementation
solutionDrive/ansible-role-grafana pull request #1
Opened 2018-07-02 08:13 UTC by sd-lueckel

2018-07-02 08:43 UTC, michz requested changes

2018-07-02 08:43 UTC, michz commented on tests/test.yml
> +    - solutiondrive.grafana
Newline

2018-07-02 09:22 UTC, michz submitted a review, later dismissed

2018-07-02 09:22 UTC, Jnoack331 submitted a review, later dismissed

2018-07-02 09:23 UTC, michz commented
Same permission problem here @solutionDrive/maintainer

2018-07-02 13:24 UTC, sd-lueckel commented
permissions should be fine now @solutionDrive/maintainer

2018-07-03 09:47 UTC, sd-lueckel commented
Ready for review again @solutionDrive/maintainer

2018-07-03 09:58 UTC, michz submitted a review, later dismissed

2018-07-03 10:13 UTC, michz approved these changes
🎉

2018-07-03 12:10 UTC, Jnoack331 approved these changes
👍

2018-07-04 12:20 UTC, mattagohni approved these changes

2018-07-04 12:21 UTC, merged